# ansible/inventory/aws_ec2.yml
plugin: aws_ec2
regions:
  - us-east-2 # !! IMPORTANT: Replace with your actual AWS region !!
keyed_groups:
  # Creates groups based on AWS resource tags.
  # For example, an instance with tag "Role: docker-host" will be in group 'tag_docker_host'.
  - key: tags.Role
    prefix: tag_
  # Creates groups based on the Environment tag (e.g., 'env_stage', 'env_production').
  - key: tags.Environment
    prefix: env_
  # Creates groups based on the Auto Scaling Group name.
  - key: tags.aws_autoscaling_groupName
    prefix: asg_

filters:
  # Only consider instances that are currently running.
  instance-state-name: running
  # Filter by your specific project tag to narrow down instances.
  "tag:Project": "your-project-name" # !! IMPORTANT: Replace with your actual project tag value !!

# Defines connection settings for instances found via this inventory.
# This is crucial for using AWS Systems Manager (SSM) as the connection method.
strict: false # Allows a playbook to define groups not all of whose hosts must exist.
compose:
  # Use private IP for connection if instances are in private subnets, which is recommended.
  ansible_host: private_ip_address

host_vars:
  # Set the connection plugin to AWS SSM for all hosts found by this inventory.
  # The target EC2 instances must have the SSM Agent installed and an IAM role with
  # `AmazonSSMManagedInstanceCore` policy.
  ansible_connection: community.aws.aws_ssm