# ansible/playbooks/deploy_application.yml
---
- name: Deploy PetClinic Application
  hosts: tag_docker-host  # All EC2s tagged with Role=docker-host
  become: true
  gather_facts: false

  vars:
    application_name: "petclinicapps"
    application_port: 8080
    host_port: 8080
    # APP_VERSION will be passed from Jenkins
    # nexus_docker_registry_url and vault_addr are defined in group_vars/all.yml

  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: true

    - name: Login to Nexus Docker Registry
      community.docker.docker_login:
        registry_url: "{{ nexus_docker_registry_url }}"
        username: "{{ lookup('community.hashi_vault.vault_read', 'secret=secret/data/nexus/docker/credentials:username', vault_addr=vault_addr) }}"
        password: "{{ lookup('community.hashi_vault.vault_read', 'secret=secret/data/nexus/docker/credentials:password', vault_addr=vault_addr) }}"
      no_log: true

    - name: Pull the Docker image from Nexus
      community.docker.docker_image:
        name: "{{ nexus_docker_registry_url }}/{{ application_name }}"
        tag: "{{ APP_VERSION }}"
        source: pull
      register: image_pull_result

    - name: Check if container is already running
      community.docker.docker_container_info:
        name: "{{ application_name }}-container"
      register: container_info_result

    - name: Stop old container if outdated
      community.docker.docker_container:
        name: "{{ application_name }}-container"
        state: absent
        force_kill: yes
      when:
        - image_pull_result.changed or
          (container_info_result.containers | default([]) | length > 0 and
           container_info_result.containers[0].Image != (nexus_docker_registry_url + '/' + application_name + ':' + APP_VERSION))

    - name: Start new application container
      community.docker.docker_container:
        name: "{{ application_name }}-container"
        image: "{{ nexus_docker_registry_url }}/{{ application_name }}:{{ APP_VERSION }}"
        state: started
        pull: no
        ports:
          - "{{ host_port }}:{{ application_port }}"
        restart_policy: unless-stopped
        env:
          DB_HOST: "{{ db_host }}"
          DB_PORT: "{{ db_port }}"
          DB_USERNAME: "{{ lookup('community.hashi_vault.vault_read', 'secret=secret/data/petclinic/database/credentials:username', vault_addr=vault_addr) }}"
          DB_PASSWORD: "{{ lookup('community.hashi_vault.vault_read', 'secret=secret/data/petclinic/database/credentials:password', vault_addr=vault_addr) }}"

  # Optional handlers can be defined here if needed
